// CONSIDER USING THIS FILE TO STORE FUNCTIONS THAT DON'T NEED TO REFER TO YOUR COMPONENT
//   (i.e. functions that don't change state. They can still return something needed for state though)
// EXAMPLES INCLUDE:
//   Average rating
//   Render stars
//   Total reviews
//     etc.

// THIS WILL PROBABLY MAKE IT EASIER TO MAKE UNIT TESTS FOR THESE
// IT'LL ALSO MAKE COMPONENTS LESS BULKY (AND POTENTIALLY LESS PROP DRILLING WITH FUNCTIONS)





// ALSO MIGHT HAVE TO CHANGE THIS FILE FROM .js TO .jsx IF NEED TO RETURN JSX?